### ISSUE TITLE
[JOSS Review] Documentation

### ISSUE THREAD

**Issue by braniii** [aadya940/chainopy#18]
Hi @aadya940,

this is part of [my review](https://github.com/openjournals/joss-reviews/issues/6880) and will be updated the next days.

Here is a list with open tasks:

- [x] Host the documentation
- [x] Fix sphinx so that the API is included in the documentation
- [x] Add examples for the advertised functionality in the docs. 
- [x] Would it be possible to include the API of the public methods, rather than of the private submodules?
- [x] Please add a short description of the 3 classes, including a short description of the attributes. Only a name without a type, e.g. `epsilon` is (at least for me) not easy to interpret.
- [x] Fix rendering issues of the README. in "the basics" section.

I've finally finished the review. If you have any questions, feel free to write me.

Kind regards
Daniel Nagel

**Comment by braniii** [comment]
Here is a list with minor issues I found while reviewing this repository. I thought it would be helpful sharing them:

- [ ] in `test_markovchain.py` line 73+74 and 88+89 are without functionality. Line 75 should be `if not (fm_x is None and fm_y is None)`:, but having a deterministic input, I guess line 75+76 are never reached and should be deleted!? The same for line 88+89. If you want to run the same test with different input parameters you can use `@pytest.mark.parametrize` , see https://docs.pytest.org/en/6.2.x/parametrize.html

**Comment by aadya940** [comment]
Yes @braniii , you are correct regarding the `test_markovchain.py`, I'll fix it soon. As for the docs, there is an issue with readthedocs, they give a 404 error which I'm unable to solve however you'll be able to build the docs locally. Also, the docs are essentially generated using the docstring so you could just refer to those as of now.

Here are the steps to generate the docs locally:

Go to the project folder:

Step - 1:

```bash
pip install -r requirements_doc.txt
```

Step - 2:

```bash
sphinx-apidoc -o docs/source chainopy/
```

Step - 3:
```bash
cd docs
make html
```

Step - 4:
```bash
cd build/html
python -m http.server
```

The docs will be listed on the given port.

**Comment by aadya940** [comment]
As for uploading the package on `pip`, I'll do it ASAP, sorry for the delay :))

**Comment by braniii** [comment]
> Yes @braniii , you are correct regarding the `test_markovchain.py`, I'll fix it soon. As for the docs, there is an issue with readthedocs, they give a 404 error which I'm unable to solve however you'll be able to build the docs locally. Also, the docs are essentially generated using the docstring so you could just refer to those as of now.
> 
> Here are the steps to generate the docs locally:
> 
> Go to the project folder:
> 
> Step - 1:
> 
> ```shell
> pip install -r requirements_doc.txt
> ```
> 
> Step - 2:
> 
> ```shell
> sphinx-apidoc -o docs/source chainopy/
> ```
> 
> Step - 3:
> 
> ```shell
> cd docs
> make html
> ```
> 
> Step - 4:
> 
> ```shell
> cd build/html
> python -m http.server
> ```
> 
> The docs will be listed on the given port.

I've managed to build the docs, but it seems that there are some markdown parsing issues. I will wait until the documentation is back online.

![Screenshot from 2024-07-10 16-06-12](https://github.com/aadya940/chainopy/assets/28560129/0e6a610f-84df-427c-a3c2-22c7682a605c)
![Screenshot from 2024-07-10 16-06-55](https://github.com/aadya940/chainopy/assets/28560129/cf00216a-46ba-4eb5-a815-faf3ea433f3f)

**Comment by aadya940** [comment]
Hi @braniii , So the docs are up and running now at :
[https://chainopy.readthedocs.io/en/latest/](https://chainopy.readthedocs.io/en/latest/)

However, I'll improve these more in the future, this is just a start so that our reviews don't get affected. :))

**Comment by braniii** [comment]
@aadya940 Sorry for this lengthy review process. But I've finally finished the review. If you have any further questions, feel free to write me.

**Comment by aadya940** [comment]
The review has been really helpful to target sections which were lacking before. Thanks for the comprehensive review :))

**Comment by braniii** [comment]
> The review has been really helpful to target sections which were lacking before. Thanks for the comprehensive review :))

You are welcome :)

**Comment by aadya940** [comment]
@braniii 
For point three: 
```
 Add examples for the advertised functionality in the docs.
```
I believe I've added plenty examples in https://github.com/aadya940/chainopy/blob/master/examples/demo.ipynb , 
So I've just referenced this file at the top of my sphinx documentation and hence am checking the box. Hope it is fine for you :))

**Comment by braniii** [comment]
> @braniii For point three:
> 
> ```
>  Add examples for the advertised functionality in the docs.
> ```
> 
> I believe I've added plenty examples in https://github.com/aadya940/chainopy/blob/master/examples/demo.ipynb , So I've just referenced this file at the top of my sphinx documentation and hence am checking the box. Hope it is fine for you :))

The issue with githubs ipynb rendering engine is, that it is still not supported in the official app. Could you therefore simply include the notebook as a new page into your docs?

**Comment by aadya940** [comment]
Yes good idea, thanks

**Comment by braniii** [comment]
@aadya940 please tick off only issues you've fixed. Both, the examples are still missing and parts of the README are not rendered.

**Comment by aadya940** [comment]
@braniii Hello, 
- The Jupyter Example Notebooks are now visible inside the docs under Examples section, you could check it out.
- I believe I've also fixed the rendering issue inside the README part.
- Attributes like epsilon being documented twice seems like a Sphinx issue since it doesn't behave well with `__slots__`, check it out here :
[https://stackoverflow.com/questions/78789259/how-to-prevent-sphinx-from-displaying-duplicate-attributes-in-class-documentatio](https://stackoverflow.com/questions/78789259/how-to-prevent-sphinx-from-displaying-duplicate-attributes-in-class-documentatio)
Could we skip it for now till I come up with a good solution?

I hope everything seems good now :)) , Sorry for the delay.

**Comment by braniii** [comment]
Looks good.
